#GET THE API KEY FROM DOODSTREAM.COM OR USE THE DEFAULT
#IF YOU DON'T HAVE API KEY YOU CAN USE DEFAULT
#BUT IF YOU HAVE YOU CAN CHANGE ON THE CODE BELOW

import os

API_KEY = "272480tnxvpqma6hzqk5vk"
API_KEY = "495078pztmrjyz299bmkd6"
